modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0"

[[mods]]
modId = "edgelesschatscreen"
version = "${version}"
displayName = "Edgeless Chat Screen"
displayURL = "https://github.com/KessokuTeaTime/Edgeless-Chat-Screen"
authors = "Kessoku Tea Time"
description = '''
Why not having an edgeless chat screen?
'''
logoFile = "icon.png"

[[mixins]]
config = "edgelesschatscreen.mixins.json"

[[dependencies.edgelesschatscreen]]
modId = "neoforge"
mandatory = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.edgelesschatscreen]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"