modLoader = "javafml"
loaderVersion = "[43,)"
license = "GPL-3.0"

[[mods]]
modId = "edgelesschatscreen"
version = "${version}"
displayName = "Stenographer"
displayURL = "https://github.com/KessokuTeaTime/Edgeless-Chat-Screen"
authors = "Kessoku Tea Time"
description = '''
Why not having an edgeless chat screen?
'''
logoFile = "icon.png"

[[dependencies.edgelesschatscreen]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.edgelesschatscreen]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"